# Mosquitto MQTT Broker Config
# Green Campus EMS Project

# Listen on ALL network interfaces (so NodeMCU can connect)
listener 1883 0.0.0.0

# Allow connections without username/password
allow_anonymous true

# Log level
log_type all
